### ISSUE TITLE
% sign after close parenthesis Progress tracker

### ISSUE THREAD

**Issue by AZRockslide** [WireJunky42/ExtraLifeStreamLabels#2] opened 2018-05-09 14:26 UTC
There is currently anothter percentage sign after the closed parenthesis on the Progress Tracker. It looked like this on stream:

116/1500 (6%)%

**Comment by WireJunky42** [comment] 2018-05-09 14:27
Can you provide a screenshot?  I cannot replicate that when I use that in a text file in OBS Studio.

**Comment by WireJunky42** [comment] 2018-05-09 14:30
![image](https://user-images.githubusercontent.com/8039354/39820528-005d6144-5374-11e8-85a1-b673ea6ca1f8.png)

**Comment by AZRockslide** [comment] 2018-05-09 14:35
![image](https://user-images.githubusercontent.com/39128398/39820820-89a98e46-535b-11e8-9316-4c20011e4cea.png)

**Comment by AZRockslide** [comment] 2018-05-09 14:35
Took that from my stream last night.

**Comment by WireJunky42** [comment] 2018-05-09 14:39
Could you open the text file that is generated for the progress stream label and confirm that it has the extra '%' in it?

**Comment by AZRockslide** [comment] 2018-05-09 14:41
When I get home, but that will be relatively late tonight.

**Comment by WireJunky42** [comment] 2018-05-10 12:17
I believe I was able to replicate this last night.  Not on the progress stream label but on the most recent donor label.  I have isolated the cause and will be fixing this in the next release.

**Comment by WireJunky42** [comment] 2018-05-10 14:57
This has been addressed and tested locally and will be included in the next release.  The issue was that I was not clearing the file stream before writing the new data.  If the new data was just the right size, your label files could be left with artifacts from the last fetched data object.  I now clear the file stream before writing the new data to the file to force a full overwrite of the file.

**Closed by WireJunky42** 2018-05-10 14:57 UTC
